default:
  variables:
    USE_DOCKER: false

stages:
  - test

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine
  script: 
    - ./run_tests.sh --shellcheck

pylint:
  stage: test
  image: python:3.8-alpine
  script:
    - ./run_tests.sh --pylint
